version: '3.8'
services:
  postgres:
    image: postgres ###will come from docker hub
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password
  redis:
    image: redis #will come from docker hub 
    ports:
      - "6379:6379"

    